In [20]:
digits=[5,6,7,8,10,12,13,17,19,21.22]

In [21]:
sqrdigits =[]
for i in digits:
    sqrdigits.append(i**2)

In [22]:
sqrdigits

[25, 36, 49, 64, 100, 144, 169, 289, 361, 450.28839999999997]

In [23]:
sqr=[i**2 for i in digits]

In [24]:
sqr

[25, 36, 49, 64, 100, 144, 169, 289, 361, 450.28839999999997]

In [25]:
h_digit=[]
for i in digits:
    if i>10:
        h_digit.append(i)

In [26]:
h_digit

[12, 13, 17, 19, 21.22]

In [27]:
high_digit=[i for i in digits if i>10]

In [28]:
high_digit

[12, 13, 17, 19, 21.22]

In [29]:
celsius=[15,17,18,21,28,59,31,23,20,35,44]

In [30]:
fahrenheit=[]
for i in celsius:
    fahrenheit.append(i*(9/5)+32)

In [31]:
fahrenheit

[59.0,
 62.6,
 64.4,
 69.80000000000001,
 82.4,
 138.2,
 87.80000000000001,
 73.4,
 68.0,
 95.0,
 111.2]

In [32]:
fahrenheit_2=[(i*(9/5)+32) for i in celsius]

In [33]:
fahrenheit_2

[59.0,
 62.6,
 64.4,
 69.80000000000001,
 82.4,
 138.2,
 87.80000000000001,
 73.4,
 68.0,
 95.0,
 111.2]

In [34]:
sales_data = [
    {"order_id": 1001, "product": "Lenovo 24-inch Monitor", "category": "Displays", "price": 149.00, "qty": 2, "status": "Shipped"},
    {"order_id": 1002, "product": "Juovi 20000mAh Power Bank", "category": "Accessories", "price": 45.50, "qty": 1, "status": "Processing"},
    {"order_id": 1003, "product": "Dell Precision Laptop", "category": "Computers", "price": 2450.00, "qty": 1, "status": "Shipped"},
    {"order_id": 1004, "product": "HEYMIX Extension Powerboard", "category": "Accessories", "price": 35.00, "qty": 3, "status": "Delivered"},
    {"order_id": 1005, "product": "Dynabook 13-inch Laptop", "category": "Computers", "price": 1150.00, "qty": 1, "status": "Shipped"},
    {"order_id": 1006, "product": "iQOO Smartphone", "category": "Mobile", "price": 850.00, "qty": 1, "status": "Cancelled"},
    {"order_id": 1007, "product": "Lenovo 24-inch Monitor", "category": "Displays", "price": 149.00, "qty": 1, "status": "Shipped"},
    {"order_id": 1008, "product": "Wireless Mouse", "category": "Peripherals", "price": 25.00, "qty": 5, "status": "Delivered"},
    {"order_id": 1009, "product": "Juovi 20000mAh Power Bank", "category": "Accessories", "price": 45.50, "qty": 2, "status": "Shipped"},
    {"order_id": 1010, "product": "Mechanical Keyboard", "category": "Peripherals", "price": 89.99, "qty": 1, "status": "Shipped"},
    {"order_id": 1011, "product": "HEYMIX Extension Powerboard", "category": "Accessories", "price": 35.00, "qty": 1, "status": "Processing"},
    {"order_id": 1012, "product": "Dell Precision Laptop", "category": "Computers", "price": 2450.00, "qty": 2, "status": "Delivered"},
    {"order_id": 1013, "product": "USB-C Hub", "category": "Accessories", "price": 29.50, "qty": 4, "status": "Shipped"},
    {"order_id": 1014, "product": "iQOO Smartphone", "category": "Mobile", "price": 850.00, "qty": 1, "status": "Shipped"},
    {"order_id": 1015, "product": "Lenovo 24-inch Monitor", "category": "Displays", "price": 149.00, "qty": 3, "status": "Cancelled"},
    {"order_id": 1016, "product": "Dynabook 13-inch Laptop", "category": "Computers", "price": 1150.00, "qty": 1, "status": "Delivered"},
    {"order_id": 1017, "product": "Noise Cancelling Headphones", "category": "Audio", "price": 199.00, "qty": 1, "status": "Shipped"},
    {"order_id": 1018, "product": "Juovi 20000mAh Power Bank", "category": "Accessories", "price": 45.50, "qty": 5, "status": "Shipped"},
    {"order_id": 1019, "product": "HEYMIX Extension Powerboard", "category": "Accessories", "price": 35.00, "qty": 2, "status": "Delivered"},
    {"order_id": 1020, "product": "Dell Precision Laptop", "category": "Computers", "price": 2450.00, "qty": 1, "status": "Processing"}
]

In [35]:
#Calculate the total realized revenue from the dataset.
total=0
for i in sales_data:
    if i["status"] in ("Shipped","Processing","Delivered"):
        total+=(i["qty"]*i["price"])

print(total)

14502.99

In [38]:
#Create a new list of dictionaries containing only high-value orders.
high_v_orders=[]
for k in sales_data:
    if i["status"] in ("Shipped", "Processing"):
        if k["qty"]*k["price"]>1000:
            high_v_orders.append({"Order_id":k["order_id"],"Product":k["product"]})
        
print (high_v_orders)

[{'Order_id': 1003, 'Product': 'Dell Precision Laptop'}, {'Order_id': 1005, 'Product': 'Dynabook 13-inch Laptop'}, {'Order_id': 1012, 'Product': 'Dell Precision Laptop'}, {'Order_id': 1016, 'Product': 'Dynabook 13-inch Laptop'}, {'Order_id': 1020, 'Product': 'Dell Precision Laptop'}]

In [39]:
import pandas as pd
import numpy as np
df =  pd.read_csv(r'C:\Users\Shaon\Downloads\Compressed\train.csv')

In [40]:
df.iloc[5000:]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
5000,5001,CA-2018-159688,07/05/2018,12/05/2018,Standard Class,AB-10060,Adam Bellavance,Home Office,United States,Los Angeles,California,90004.0,West,TEC-AC-10000736,Technology,Accessories,Logitech G600 MMO Gaming Mouse,79.990
5001,5002,CA-2017-136126,24/05/2017,24/05/2017,Same Day,EH-14125,Eugene Hildebrand,Home Office,United States,Newport News,Virginia,23602.0,South,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,69.500
5002,5003,CA-2017-136126,24/05/2017,24/05/2017,Same Day,EH-14125,Eugene Hildebrand,Home Office,United States,Newport News,Virginia,23602.0,South,OFF-PA-10004327,Office Supplies,Paper,Xerox 1911,191.600
5003,5004,CA-2017-155033,07/10/2017,12/10/2017,Standard Class,CC-12475,Cindy Chapman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-PA-10000143,Office Supplies,Paper,Astroparche Fine Business Paper,10.560
5004,5005,CA-2015-156006,30/04/2015,02/05/2015,Second Class,TM-21010,Tamara Manning,Consumer,United States,Jackson,Mississippi,39212.0,South,TEC-AC-10002550,Technology,Accessories,Maxell 4.7GB DVD-RW 3/Pack,47.790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [41]:
df.loc[0:5,"Sales"]

0    261.9600
1    731.9400
2     14.6200
3    957.5775
4     22.3680
5     48.8600
Name: Sales, dtype: float64

In [43]:
df[(df["Sales"] > 1000) & (df["City"].isin (["Florida","Orem", "Toledo"]))]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
24,25,CA-2016-106320,25/09/2016,30/09/2016,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057.0,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630
2558,2559,CA-2016-147788,31/05/2016,04/06/2016,Standard Class,TM-21010,Tamara Manning,Consumer,United States,Orem,Utah,84057.0,West,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,1406.860
5016,5017,CA-2015-153850,24/11/2015,29/11/2015,Standard Class,TH-21100,Thea Hendricks,Consumer,United States,Toledo,Ohio,43615.0,East,TEC-PH-10002584,Technology,Phones,Samsung Galaxy S4,1502.376

In [44]:
df.loc[0:5,["Customer Name","State","Category","Sales"]]

     Customer Name       State         Category     Sales
0      Claire Gute    Kentucky        Furniture  261.9600
1      Claire Gute    Kentucky        Furniture  731.9400
2  Darrin Van Huff  California  Office Supplies   14.6200
3   Sean O'Donnell     Florida        Furniture  957.5775
4   Sean O'Donnell     Florida  Office Supplies   22.3680
5  Brosina Hoffman  California        Furniture   48.8600

In [45]:
df.loc[df["Sales"]>2000,"Order ID"]

27      US-2016-150630
165     CA-2015-139892
244     CA-2015-131926
251     CA-2017-145625
262     US-2015-106992
             ...
9639    CA-2016-116638
9649    CA-2017-107104
9660    CA-2017-160717
9741    CA-2016-117086
9774    CA-2015-169019
Name: Order ID, Length: 137, dtype: object

In [46]:
df.loc[(df["Region"]=="West")&(df["Sales"]>1000),"Order ID"]

10      CA-2015-115812
24      CA-2016-106320
67      CA-2015-106376
251     CA-2017-145625
282     CA-2016-130890
             ...
9490    CA-2018-111738
9615    CA-2015-128524
9649    CA-2017-107104
9660    CA-2017-160717
9759    CA-2017-146913
Name: Order ID, Length: 157, dtype: object

In [47]:
df.loc[(df["Region"]=="West")&(df["Sales"]>1000),["Customer Name","State","Product Name","Sales"]]

,Customer Name,State,Product Name,Sales
10,Brosina Hoffman,California,Chromcraft Rectangular Conference Tables,1706.184
24,Emily Burns,Utah,Bretford CR4500 Series Slim Rectangular Table,1044.630
67,Brendan Sweed,Arizona,Hunt BOSTON Model 1606 High-Volume Electric Pe...,1113.024
251,Kelly Collister,California,Logitech P710e Mobile Speakerphone,3347.370
282,Jas O'Carroll,California,"Bevis Round Bullnose 29"" High Table Top",1038.840
...,...,...,...,...
9490,Christopher Martinez,California,GBC ProClick 150 Presentation Binding System,2022.272
9615,Mary Zewe,Washington,Fellowes PB500 Electric Punch Plastic Comb Bin...,2033.584
9649,Maribeth Schnelling,California,DMI Eclipse Executive Suite Bookcases,3406.664
9660,Maria Etezadi,California,Samsung Galaxy Mega 6.3,3023.928
9759,Sylvia Foulston,California,Office Star - Professional Matrix Back Chair w...,1403.920

In [48]:
df[(df["Sales"]>500)&(df["Sales"]<1000)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
11,12,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240
16,17,CA-2015-105893,11/11/2015,18/11/2015,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711.0,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9732,9733,CA-2015-114321,20/08/2015,25/08/2015,Standard Class,NC-18535,Nick Crebassa,Corporate,United States,Hampton,Virginia,23666.0,South,FUR-CH-10001797,Furniture,Chairs,"Safco Chair Connectors, 6/Carton",500.2400
9734,9735,CA-2015-114321,20/08/2015,25/08/2015,Standard Class,NC-18535,Nick Crebassa,Corporate,United States,Hampton,Virginia,23666.0,South,OFF-BI-10001359,Office Supplies,Binders,GBC DocuBind TL300 Electric Binding System,896.9900
9748,9749,US-2015-140914,11/11/2015,15/11/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Chicago,Illinois,60653.0,Central,FUR-CH-10003379,Furniture,Chairs,Global Commerce Series High-Back Swivel/Tilt C...,797.9440
9781,9782,CA-2017-153178,14/09/2017,18/09/2017,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Long Beach,New York,11561.0,East,OFF-BI-10004390,Office Supplies,Binders,GBC DocuBind 200 Manual Binding Machine,673.5680
9788,9789,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,600.5580

In [49]:
#How many Technology orders are from the West region?
df[(df["Category"]=="Technology")&(df["Region"]=="South")]["Region"].value_counts()

Region
South    289
Name: count, dtype: int64

In [50]:
df["Sale_level"]=np.where(df["Sales"]>1000,"High","Low")

In [51]:
range = df.iloc[1000:6005]
range.loc[df["Sale_level"]=="High","Order ID"].shape[0]

226

In [52]:
df["Name upper"]=df["Customer Name"].str.upper()

In [53]:
df["Name upper"]

0            CLAIRE GUTE
1            CLAIRE GUTE
2        DARRIN VAN HUFF
3         SEAN O'DONNELL
4         SEAN O'DONNELL
              ...
9795       SALLY HUGHSBY
9796    CINDY SCHNELLING
9797    CINDY SCHNELLING
9798    CINDY SCHNELLING
9799    CINDY SCHNELLING
Name: Name upper, Length: 9800, dtype: object

In [54]:
df=df.drop(columns="Name upper")
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Sale_level
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,Low
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,Low
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,Low
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,Low
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,Low

In [56]:
sales_array = df["Sales"].to_numpy()

In [57]:
np.mean(sales_array)

np.float64(230.76905945918367)

In [58]:
sales_array[sales_array>2000]

array([ 3083.43  ,  8159.952 ,  2001.86  ,  3347.37  ,  3059.982 ,
        2519.958 ,  3991.98  ,  4355.168 ,  2396.2656,  2735.952 ,
        6354.95  ,  2999.95  ,  7999.98  ,  2065.32  ,  3059.982 ,
        2715.93  ,  2309.65  ,  4899.93  ,  2244.48  ,  3610.848 ,
        2453.43  ,  3040.    ,  3149.93  ,  2807.84  ,  4663.736 ,
        2575.944 ,  3999.95  ,  2396.4   ,  4548.81  ,  8187.65  ,
        2665.62  , 11199.968 ,  2399.6   , 22638.48  ,  2690.97  ,
        2549.985 ,  2054.272 ,  2799.96  ,  2934.33  ,  2025.36  ,
        3359.952 ,  4164.05  ,  2504.74  ,  2395.2   ,  2430.08  ,
        2060.744 ,  2003.52  ,  2799.96  ,  2591.56  ,  3080.    ,
        9449.95  ,  2624.985 , 10499.97  ,  4799.984 ,  9099.93  ,
        4367.896 ,  2879.952 ,  2404.704 ,  2249.91  ,  2321.9   ,
        2799.96  ,  3504.9   ,  3930.072 ,  2275.5   ,  2314.116 ,
        2479.96  ,  2999.95  ,  2348.82  ,  2799.944 ,  4912.59  ,
        4228.704 ,  2003.92  ,  2357.488 ,  2548.56  ,  4158.912 ,
        2888.127 ,  2254.41  ,  2279.96  ,  2793.528 ,  5199.96  ,
        8399.976 ,  2079.4   ,  5443.96  ,  2152.776 ,  4007.84  ,
        4164.05  ,  6999.96  ,  3266.376 , 17499.95  ,  2887.056 ,
        2003.92  ,  2567.84  ,  2399.96  ,  2399.96  ,  4416.174 ,
        2541.98  ,  2573.82  ,  2249.91  ,  2625.12  ,  3499.93  ,
        5399.91  ,  3812.97  ,  4499.985 ,  4535.976 ,  3404.5   ,
        2518.29  ,  3357.6   ,  2973.32  , 13999.96  ,  2036.86  ,
        4643.8   ,  2803.92  ,  2003.168 ,  2563.056 ,  2939.93  ,
        2154.9   ,  2678.94  ,  8749.95  ,  2104.55  ,  2239.936 ,
        3050.376 ,  5083.96  ,  2676.672 ,  4899.93  ,  9892.74  ,
        2621.322 ,  4476.8   ,  4305.552 ,  2803.92  ,  3785.292 ,
        2022.272 ,  2033.584 ,  4297.644 ,  3406.664 ,  3023.928 ,
        4404.9   ,  2177.584 ])

In [59]:
prices = np.array([80,52,46,200,148,32,58,799,600])

In [60]:
start = np.where(prices==148)[0][0]
end = np.where(prices==799)[0][0]
prices[start:end+1]

array([148,  32,  58, 799])

In [61]:
prices[(prices>=80) & (prices<=200)]

array([ 80, 200, 148])

In [66]:
increase_price= 1.1*prices

In [67]:
increase_price

array([ 88. ,  57.2,  50.6, 220. , 162.8,  35.2,  63.8, 878.9, 660. ])

In [70]:
Twod_data=np.array([[41,59,63,22],
                [400,26,347,144],
                [10,58,6,97],
                [78,887,96,20]])
Twod_data

array([[ 41,  59,  63,  22],
       [400,  26, 347, 144],
       [ 10,  58,   6,  97],
       [ 78, 887,  96,  20]])

In [92]:
#Twod_data[:,0].mean()
np.mean(Twod_data,axis=0)

array([132.25, 257.5 , 128.  ,  70.75])

In [84]:
Twod_data[:,:3]

array([[ 41,  59,  63],
       [400,  26, 347],
       [ 10,  58,   6],
       [ 78, 887,  96]])

In [93]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Sale_level
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,Low
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,Low
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,Low

In [96]:
df.groupby("State")["Sales"].sum().reset_index(name="Total_sales")

                   State  Total_sales
0                Alabama   19510.6400
1                Arizona   35272.6570
2               Arkansas   11678.1300
3             California  446306.4635
4               Colorado   31841.5980
5            Connecticut   13384.3570
6               Delaware   27322.9990
7   District of Columbia    2865.0200
8                Florida   88436.5320
9                Georgia   48219.1100
10                 Idaho    4382.4860
11              Illinois   79236.5170
12               Indiana   48718.4000
13                  Iowa    4443.5600
14                Kansas    2914.3100
15              Kentucky   36458.3900
16             Louisiana    9131.0500
17                 Maine    1270.5300
18              Maryland   23705.5230
19         Massachusetts   28634.4340
20              Michigan   76136.0740
21             Minnesota   29863.1500
22           Mississippi   10771.3400
23              Missouri   22205.1500
24               Montana    5589.3520
25              Nebraska    7464.9300
26                Nevada   16729.1020
27         New Hampshire    7292.5240
28            New Jersey   34610.9720
29            New Mexico    4783.5220
30              New York  306361.1470
31        North Carolina   55165.9640
32          North Dakota     919.9100
33                  Ohio   75130.3500
34              Oklahoma   19683.3900
35                Oregon   17284.4620
36          Pennsylvania  116276.6500
37          Rhode Island   22525.0260
38        South Carolina    8481.7100
39          South Dakota    1315.5600
40             Tennessee   30661.8730
41                 Texas  168572.5322
42                  Utah   11220.0560
43               Vermont    8929.3700
44              Virginia   70636.7200
45            Washington  135206.8500
46         West Virginia    1209.8240
47             Wisconsin   31173.4300
48               Wyoming    1603.1360

In [101]:
round(df.groupby("Region")["Sales"].agg(["sum","mean","max","min"]),2)

               sum    mean       max   min
Region
Central  492646.91  216.36  17499.95  0.44
East     669518.73  240.40  11199.97  0.85
South    389151.46  243.52  22638.48  1.17
West     710219.68  226.18  13999.96  0.99

In [108]:
df.groupby("Region").agg(Total_Sales=("Sales","sum"), mean_Amount=("Sales","mean"))

         Total_Sales  mean_Amount
Region
Central  492646.9132   216.357889
East     669518.7260   240.401697
South    389151.4590   243.524067
West     710219.6845   226.184613

In [137]:
df.groupby(["Category","Sub-Category"])["Sales"].sum().reset_index(name="Highest_sales")

           Category Sub-Category  Highest_sales
0         Furniture    Bookcases    113813.1987
1         Furniture       Chairs    322822.7310
2         Furniture  Furnishings     89212.0180
3         Furniture       Tables    202810.6280
4   Office Supplies   Appliances    104618.4030
5   Office Supplies          Art     26705.4100
6   Office Supplies      Binders    200028.7850
7   Office Supplies    Envelopes     16128.0460
8   Office Supplies    Fasteners      3001.9600
9   Office Supplies       Labels     12347.7260
10  Office Supplies        Paper     76828.3040
11  Office Supplies      Storage    219343.3920
12  Office Supplies     Supplies     46420.3080
13       Technology  Accessories    164186.7000
14       Technology      Copiers    146248.0940
15       Technology     Machines    189238.6310
16       Technology       Phones    327782.4480

In [136]:
Filter_category=df.groupby(["Category","Sub-Category"])["Sales"].sum().reset_index(name="Highest_sales")
sorting_sub=Filter_category.sort_values("Highest_sales",ascending=False)
sorting_sub.drop_duplicates(subset=["Category"],keep="first")

           Category Sub-Category  Highest_sales
16       Technology       Phones     327782.448
1         Furniture       Chairs     322822.731
11  Office Supplies      Storage     219343.392

In [143]:
Filter_category=df.groupby(["Category","Sub-Category"])["Sales"].sum().reset_index(name="Highest_sales")
best_rows=Filter_category.groupby("Category")["Highest_sales"].idxmax()
Filter_category.loc[best_rows]

           Category Sub-Category  Highest_sales
1         Furniture       Chairs     322822.731
11  Office Supplies      Storage     219343.392
16       Technology       Phones     327782.448